-- Board Sample Data
INSERT INTO board VALUES ( 1, 'FreeBoard', '제목1', 'User1', 0, 0, TO_CHAR( sysdate,  'YYYY-MM-DD' ), null, '내용1', 0 );
INSERT INTO board VALUES ( 2, 'FreeBoard', '제목2', 'User2', 0, 0, TO_CHAR( sysdate,  'YYYY-MM-DD' ), null, '내용2', 0 );
INSERT INTO board VALUES ( 3, 'FreeBoard', '제목3', 'User3', 0, 0, TO_CHAR( sysdate,  'YYYY-MM-DD' ), null, '내용3', 0 );
INSERT INTO board VALUES ( 4, 'FreeBoard', '제목4', 'User4', 0, 0, TO_CHAR( sysdate,  'YYYY-MM-DD' ), null, '내용4', 0 );
INSERT INTO board VALUES ( 5, 'FreeBoard', '제목5', 'User5', 0, 0, TO_CHAR( sysdate,  'YYYY-MM-DD' ), null, '내용5', 0 );
INSERT INTO board VALUES ( 6, 'FreeBoard', '제목6', 'User6', 0, 0, TO_CHAR( sysdate,  'YYYY-MM-DD' ), null, '내용6', 0 );
INSERT INTO board VALUES ( 7, 'FreeBoard', '제목7', 'User7', 0, 0, TO_CHAR( sysdate,  'YYYY-MM-DD' ), null, '내용7', 0 );
INSERT INTO board VALUES ( 8, 'FreeBoard', '제목8', 'User8', 0, 0, TO_CHAR( sysdate,  'YYYY-MM-DD' ), null, '내용8', 0 );
INSERT INTO board VALUES ( 9, 'FreeBoard', '제목9', 'User9', 0, 0, TO_CHAR( sysdate,  'YYYY-MM-DD' ), null, '내용9', 0 );
INSERT INTO board VALUES ( 10, 'FreeBoard', '제목10', 'User10', 0, 0, TO_CHAR( sysdate,  'YYYY-MM-DD' ), null, '내용10', 0 );
INSERT INTO board VALUES ( 11, 'FreeBoard', '제목11', 'User11', 0, 0, TO_CHAR( sysdate,  'YYYY-MM-DD' ), null, '내용11', 0 );
INSERT INTO board VALUES ( 12, 'FreeBoard', '제목12', 'User12', 0, 0, TO_CHAR( sysdate,  'YYYY-MM-DD' ), null, '내용12', 0 );
INSERT INTO board VALUES ( 13, 'FreeBoard', '제목13', 'User13', 0, 0, TO_CHAR( sysdate,  'YYYY-MM-DD' ), null, '내용13', 0 );
INSERT INTO board VALUES ( 14, 'FreeBoard', '제목14', 'User14', 0, 0, TO_CHAR( sysdate,  'YYYY-MM-DD' ), null, '내용14', 0 );
INSERT INTO board VALUES ( 15, 'FreeBoard', '제목15', 'User15', 0, 0, TO_CHAR( sysdate,  'YYYY-MM-DD' ), null, '내용15', 0 );
INSERT INTO board VALUES ( 16, 'FreeBoard', '제목16', 'User16', 0, 0, TO_CHAR( sysdate,  'YYYY-MM-DD' ), null, '내용16', 0 );
INSERT INTO board VALUES ( 17, 'FreeBoard', '제목17', 'User17', 0, 0, TO_CHAR( sysdate,  'YYYY-MM-DD' ), null, '내용17', 0 );
INSERT INTO board VALUES ( 18, 'FreeBoard', '제목18', 'User18', 0, 0, TO_CHAR( sysdate,  'YYYY-MM-DD' ), null, '내용18', 0 );
INSERT INTO board VALUES ( 19, 'FreeBoard', '제목19', 'User19', 0, 0, TO_CHAR( sysdate,  'YYYY-MM-DD' ), null, '내용19', 0 );
INSERT INTO board VALUES ( 20, 'FreeBoard', '제목20', 'User20', 0, 0, TO_CHAR( sysdate,  'YYYY-MM-DD' ), null, '내용20', 0 );
INSERT INTO board VALUES ( 21, 'FreeBoard', '제목21', 'User21', 0, 0, TO_CHAR( sysdate,  'YYYY-MM-DD' ), null, '내용21', 0 );
INSERT INTO board VALUES ( 22, 'FreeBoard', '제목22', 'User22', 0, 0, TO_CHAR( sysdate,  'YYYY-MM-DD' ), null, '내용22', 0 );
INSERT INTO board VALUES ( 23, 'FreeBoard', '제목23', 'User23', 0, 0, TO_CHAR( sysdate,  'YYYY-MM-DD' ), null, '내용23', 0 );
INSERT INTO board VALUES ( 24, 'FreeBoard', '제목24', 'User24', 0, 0, TO_CHAR( sysdate,  'YYYY-MM-DD' ), null, '내용24', 0 );
INSERT INTO board VALUES ( 25, 'FreeBoard', '제목25', 'User25', 0, 0, TO_CHAR( sysdate,  'YYYY-MM-DD' ), null, '내용25', 0 );
INSERT INTO board VALUES ( 26, 'FreeBoard', '제목26', 'User26', 0, 0, TO_CHAR( sysdate,  'YYYY-MM-DD' ), null, '내용26', 0 );
INSERT INTO board VALUES ( 27, 'FreeBoard', '제목27', 'User27', 0, 0, TO_CHAR( sysdate,  'YYYY-MM-DD' ), null, '내용27', 0 );
INSERT INTO board VALUES ( 28, 'FreeBoard', '제목28', 'User28', 0, 0, TO_CHAR( sysdate,  'YYYY-MM-DD' ), null, '내용28', 0 );
INSERT INTO board VALUES ( 29, 'FreeBoard', '제목29', 'User29', 0, 0, TO_CHAR( sysdate,  'YYYY-MM-DD' ), null, '내용29', 0 );
INSERT INTO board VALUES ( 30, 'FreeBoard', '제목30', 'User30', 0, 0, TO_CHAR( sysdate,  'YYYY-MM-DD' ), null, '내용30', 0 );

-- commit;
-- DELETE FROM board WHERE board_no BETWEEN 1 AND 30;