INSERT INTO "location" VALUES( 1 ,'서울');
INSERT INTO "location" VALUES( 2 ,'부산');
INSERT INTO "location" VALUES( 3 ,'대구');
INSERT INTO "location" VALUES( 4 ,'인천');
INSERT INTO "location" VALUES( 5 ,'광주');
INSERT INTO "location" VALUES( 6 ,'대전');
INSERT INTO "location" VALUES( 7 ,'울산');
INSERT INTO "location" VALUES( 8 ,'세종');
INSERT INTO "location" VALUES( 9 ,'경기');
INSERT INTO "location" VALUES( 10 ,'강원');
INSERT INTO "location" VALUES( 11 ,'충청');
INSERT INTO "location" VALUES( 12 ,'전라');
INSERT INTO "location" VALUES( 13 ,'경상');
INSERT INTO "location" VALUES( 14 ,'제주');


INSERT INTO "project" VALUES( 1 , 1 ,'프로젝트명1', TO_CHAR( sysdate, 'YYYY-MM-DD' ), TO_CHAR( sysdate, 'YYYY-MM-DD' ),'프로젝트 내용1', 10 ,'user1@naver.com');
INSERT INTO "project" VALUES( 2 , 2 ,'프로젝트명2', TO_CHAR( sysdate, 'YYYY-MM-DD' ), TO_CHAR( sysdate, 'YYYY-MM-DD' ),'프로젝트 내용2', 10 ,'user2@naver.com');
INSERT INTO "project" VALUES( 3 , 3 ,'프로젝트명3', TO_CHAR( sysdate, 'YYYY-MM-DD' ), TO_CHAR( sysdate, 'YYYY-MM-DD' ),'프로젝트 내용3', 10 ,'user3@naver.com');
INSERT INTO "project" VALUES( 4 , 4 ,'프로젝트명4', TO_CHAR( sysdate, 'YYYY-MM-DD' ), TO_CHAR( sysdate, 'YYYY-MM-DD' ),'프로젝트 내용4', 10 ,'user4@naver.com');
INSERT INTO "project" VALUES( 5 , 5 ,'프로젝트명5', TO_CHAR( sysdate, 'YYYY-MM-DD' ), TO_CHAR( sysdate, 'YYYY-MM-DD' ),'프로젝트 내용5', 10 ,'user5@naver.com');
INSERT INTO "project" VALUES( 6 , 6 ,'프로젝트명6', TO_CHAR( sysdate, 'YYYY-MM-DD' ), TO_CHAR( sysdate, 'YYYY-MM-DD' ),'프로젝트 내용6', 10 ,'user6@naver.com');
INSERT INTO "project" VALUES( 7 , 7 ,'프로젝트명7', TO_CHAR( sysdate, 'YYYY-MM-DD' ), TO_CHAR( sysdate, 'YYYY-MM-DD' ),'프로젝트 내용7', 10 ,'user7@naver.com');
INSERT INTO "project" VALUES( 8 , 8 ,'프로젝트명8', TO_CHAR( sysdate, 'YYYY-MM-DD' ), TO_CHAR( sysdate, 'YYYY-MM-DD' ),'프로젝트 내용8', 10 ,'user8@naver.com');
INSERT INTO "project" VALUES( 9 , 9 ,'프로젝트명9', TO_CHAR( sysdate, 'YYYY-MM-DD' ), TO_CHAR( sysdate, 'YYYY-MM-DD' ),'프로젝트 내용9', 10 ,'user9@naver.com');
INSERT INTO "project" VALUES( 10 , 10 ,'프로젝트명10', TO_CHAR( sysdate, 'YYYY-MM-DD' ), TO_CHAR( sysdate, 'YYYY-MM-DD' ),'프로젝트 내용10', 10 ,'user10@naver.com');
INSERT INTO "project" VALUES( 11 , 11 ,'프로젝트명11', TO_CHAR( sysdate, 'YYYY-MM-DD' ), TO_CHAR( sysdate, 'YYYY-MM-DD' ),'프로젝트 내용11', 10 ,'user1@naver.com');
INSERT INTO "project" VALUES( 12 , 12 ,'프로젝트명12', TO_CHAR( sysdate, 'YYYY-MM-DD' ), TO_CHAR( sysdate, 'YYYY-MM-DD' ),'프로젝트 내용12', 10 ,'user2@naver.com');
INSERT INTO "project" VALUES( 13 , 13 ,'프로젝트명13', TO_CHAR( sysdate, 'YYYY-MM-DD' ), TO_CHAR( sysdate, 'YYYY-MM-DD' ),'프로젝트 내용13', 10 ,'user3@naver.com');
INSERT INTO "project" VALUES( 14 , 14 ,'프로젝트명14', TO_CHAR( sysdate, 'YYYY-MM-DD' ), TO_CHAR( sysdate, 'YYYY-MM-DD' ),'프로젝트 내용14', 10 ,'user4@naver.com');
INSERT INTO "project" VALUES( 15 , 1 ,'프로젝트명15', TO_CHAR( sysdate, 'YYYY-MM-DD' ), TO_CHAR( sysdate, 'YYYY-MM-DD' ),'프로젝트 내용15', 10 ,'user5@naver.com');
INSERT INTO "project" VALUES( 16 , 2 ,'프로젝트명16', TO_CHAR( sysdate, 'YYYY-MM-DD' ), TO_CHAR( sysdate, 'YYYY-MM-DD' ),'프로젝트 내용16', 10 ,'user6@naver.com');
INSERT INTO "project" VALUES( 17 , 3 ,'프로젝트명17', TO_CHAR( sysdate, 'YYYY-MM-DD' ), TO_CHAR( sysdate, 'YYYY-MM-DD' ),'프로젝트 내용17', 10 ,'user7@naver.com');
INSERT INTO "project" VALUES( 18 , 4 ,'프로젝트명18', TO_CHAR( sysdate, 'YYYY-MM-DD' ), TO_CHAR( sysdate, 'YYYY-MM-DD' ),'프로젝트 내용18', 10 ,'user8@naver.com');

INSERT INTO tech VALUES( 1 ,'JAVA');
INSERT INTO tech VALUES( 2 ,'C++');
INSERT INTO tech VALUES( 3 ,'C#');
INSERT INTO tech VALUES( 4 ,'javaScript');
INSERT INTO tech VALUES( 5 ,'CSS');
INSERT INTO tech VALUES( 6 ,'HTML');
INSERT INTO tech VALUES( 7 ,'Node.js');
INSERT INTO tech VALUES( 8 ,'Oracle');
INSERT INTO tech VALUES( 9 ,'MySQL');
INSERT INTO tech VALUES( 10 ,'JSP/Servlet');
INSERT INTO tech VALUES( 11 ,'Python');
INSERT INTO tech VALUES( 12 ,'PHP');
INSERT INTO tech VALUES( 13 ,'Ruby');
INSERT INTO tech VALUES( 14 ,'Angular.js');
INSERT INTO tech VALUES( 15 ,'react');
INSERT INTO tech VALUES( 16 ,'vue.js');


INSERT INTO project_tech VALUES( 1 , 1 );
INSERT INTO project_tech VALUES( 2 , 2 );
INSERT INTO project_tech VALUES( 3 , 3 );
INSERT INTO project_tech VALUES( 4 , 4 );
INSERT INTO project_tech VALUES( 5 , 5 );
INSERT INTO project_tech VALUES( 6 , 6 );
INSERT INTO project_tech VALUES( 7 , 7 );
INSERT INTO project_tech VALUES( 8 , 8 );
INSERT INTO project_tech VALUES( 9 , 9 );
INSERT INTO project_tech VALUES( 10 , 10 );
INSERT INTO project_tech VALUES( 11 , 11 );
INSERT INTO project_tech VALUES( 12 , 12 );
INSERT INTO project_tech VALUES( 13 , 13 );
INSERT INTO project_tech VALUES( 14 , 14 );
INSERT INTO project_tech VALUES( 15 , 15 );
INSERT INTO project_tech VALUES( 16 , 16 );
INSERT INTO project_tech VALUES( 17 , 1 );
INSERT INTO project_tech VALUES( 18 , 2 );
INSERT INTO project_tech VALUES( 19 , 3 );
INSERT INTO project_tech VALUES( 20 , 4 );
INSERT INTO project_tech VALUES( 21 , 5 );
INSERT INTO project_tech VALUES( 1 , 2 );
INSERT INTO project_tech VALUES( 2 , 3 );
INSERT INTO project_tech VALUES( 3 , 4 );
INSERT INTO project_tech VALUES( 4 , 5 );
INSERT INTO project_tech VALUES( 5 , 6 );
INSERT INTO project_tech VALUES( 6 , 7 );
INSERT INTO project_tech VALUES( 7 , 8 );
INSERT INTO project_tech VALUES( 8 , 9 );
INSERT INTO project_tech VALUES( 9 , 10 );
INSERT INTO project_tech VALUES( 10 , 11 );
INSERT INTO project_tech VALUES( 11 , 12 );
INSERT INTO project_tech VALUES( 12 , 13 );
INSERT INTO project_tech VALUES( 13 , 14 );
INSERT INTO project_tech VALUES( 14 , 15 );
INSERT INTO project_tech VALUES( 15 , 16 );
INSERT INTO project_tech VALUES( 16 , 1 );
INSERT INTO project_tech VALUES( 17 , 2 );
INSERT INTO project_tech VALUES( 18 , 3 );
INSERT INTO project_tech VALUES( 19 , 4 );
INSERT INTO project_tech VALUES( 20 , 5 );
INSERT INTO project_tech VALUES( 21 , 6 );

--commit;
