-- Recruit Sample Data
INSERT INTO board VALUES( 4000, 'Recruit', '제목_구인구직1', 'User40', 0, 0, TO_CHAR( sysdate-4, 'YYYY-MM-DD' ), null, '내용_구인구직1', 0 );
INSERT INTO board VALUES( 4001, 'Recruit', '제목_구인구직2', 'User10', 0, 0, TO_CHAR( sysdate-3, 'YYYY-MM-DD' ), null, '내용_구인구직2', 0 );
INSERT INTO board VALUES( 4002, 'Recruit', '제목_구인구직3', 'User11', 0, 0, TO_CHAR( sysdate-3, 'YYYY-MM-DD' ), null, '내용_구인구직3', 0 );
INSERT INTO board VALUES( 4003, 'Recruit', '제목_구인구직4', 'User12', 0, 0, TO_CHAR( sysdate-3, 'YYYY-MM-DD' ), null, '내용_구인구직4', 0 );
INSERT INTO board VALUES( 4004, 'Recruit', '제목_구인구직5', 'User13', 0, 0, TO_CHAR( sysdate-3, 'YYYY-MM-DD' ), null, '내용_구인구직5', 0 );
INSERT INTO board VALUES( 4005, 'Recruit', '제목_구인구직6', 'User14', 0, 0, TO_CHAR( sysdate-3, 'YYYY-MM-DD' ), null, '내용_구인구직6', 0 );
INSERT INTO board VALUES( 4006, 'Recruit', '제목_구인구직7', 'User15', 0, 0, TO_CHAR( sysdate-3, 'YYYY-MM-DD' ), null, '내용_구인구직7', 0 );
INSERT INTO board VALUES( 4007, 'Recruit', '제목_구인구직8', 'User16', 0, 0, TO_CHAR( sysdate-3, 'YYYY-MM-DD' ), null, '내용_구인구직8', 0 );
INSERT INTO board VALUES( 4008, 'Recruit', '제목_구인구직9', 'User17', 0, 0, TO_CHAR( sysdate-3, 'YYYY-MM-DD' ), null, '내용_구인구직9', 0 );
INSERT INTO board VALUES( 4009, 'Recruit', '제목_구인구직10', 'User18', 0, 0, TO_CHAR( sysdate-3, 'YYYY-MM-DD' ), null, '내용_구인구직10', 0 );
INSERT INTO board VALUES( 4010, 'Recruit', '제목_구인구직11', 'User19', 0, 0, TO_CHAR( sysdate-2, 'YYYY-MM-DD' ), null, '내용_구인구직11', 0 );
INSERT INTO board VALUES( 4011, 'Recruit', '제목_구인구직12', 'User20', 0, 0, TO_CHAR( sysdate-2, 'YYYY-MM-DD' ), null, '내용_구인구직12', 0 );
INSERT INTO board VALUES( 4012, 'Recruit', '제목_구인구직13', 'User21', 0, 0, TO_CHAR( sysdate-2, 'YYYY-MM-DD' ), null, '내용_구인구직13', 0 );
INSERT INTO board VALUES( 4013, 'Recruit', '제목_구인구직14', 'User22', 0, 0, TO_CHAR( sysdate-2, 'YYYY-MM-DD' ), null, '내용_구인구직14', 0 );
INSERT INTO board VALUES( 4014, 'Recruit', '제목_구인구직15', 'User23', 0, 0, TO_CHAR( sysdate-2, 'YYYY-MM-DD' ), null, '내용_구인구직15', 0 );
INSERT INTO board VALUES( 4015, 'Recruit', '제목_구인구직16', 'User24', 0, 0, TO_CHAR( sysdate-2, 'YYYY-MM-DD' ), null, '내용_구인구직16', 0 );
INSERT INTO board VALUES( 4016, 'Recruit', '제목_구인구직17', 'User25', 0, 0, TO_CHAR( sysdate-2, 'YYYY-MM-DD' ), null, '내용_구인구직17', 0 );
INSERT INTO board VALUES( 4017, 'Recruit', '제목_구인구직18', 'User26', 0, 0, TO_CHAR( sysdate-2, 'YYYY-MM-DD' ), null, '내용_구인구직18', 0 );
INSERT INTO board VALUES( 4018, 'Recruit', '제목_구인구직19', 'User27', 0, 0, TO_CHAR( sysdate-2, 'YYYY-MM-DD' ), null, '내용_구인구직19', 0 );
INSERT INTO board VALUES( 4019, 'Recruit', '제목_구인구직20', 'User28', 0, 0, TO_CHAR( sysdate-2, 'YYYY-MM-DD' ), null, '내용_구인구직20', 0 );
INSERT INTO board VALUES( 4020, 'Recruit', '제목_구인구직21', 'User29', 0, 0, TO_CHAR( sysdate-2, 'YYYY-MM-DD' ), null, '내용_구인구직21', 0 );
INSERT INTO board VALUES( 4021, 'Recruit', '제목_구인구직22', 'User30', 0, 0, TO_CHAR( sysdate-2, 'YYYY-MM-DD' ), null, '내용_구인구직22', 0 );
INSERT INTO board VALUES( 4022, 'Recruit', '제목_구인구직23', 'User31', 0, 0, TO_CHAR( sysdate-1, 'YYYY-MM-DD' ), null, '내용_구인구직23', 0 );
INSERT INTO board VALUES( 4023, 'Recruit', '제목_구인구직24', 'User32', 0, 0, TO_CHAR( sysdate-1, 'YYYY-MM-DD' ), null, '내용_구인구직24', 0 );
INSERT INTO board VALUES( 4024, 'Recruit', '제목_구인구직25', 'User33', 0, 0, TO_CHAR( sysdate-1, 'YYYY-MM-DD' ), null, '내용_구인구직25', 0 );
INSERT INTO board VALUES( 4025, 'Recruit', '제목_구인구직26', 'User34', 0, 0, TO_CHAR( sysdate-1, 'YYYY-MM-DD' ), null, '내용_구인구직26', 0 );
INSERT INTO board VALUES( 4026, 'Recruit', '제목_구인구직27', 'User35', 0, 0, TO_CHAR( sysdate-1, 'YYYY-MM-DD' ), null, '내용_구인구직27', 0 );
INSERT INTO board VALUES( 4027, 'Recruit', '제목_구인구직28', 'User36', 0, 0, TO_CHAR( sysdate-1, 'YYYY-MM-DD' ), null, '내용_구인구직28', 0 );
INSERT INTO board VALUES( 4028, 'Recruit', '제목_구인구직29', 'User37', 0, 0, TO_CHAR( sysdate, 'YYYY-MM-DD' ), null, '내용_구인구직29', 0 );
INSERT INTO board VALUES( 4029, 'Recruit', '제목_구인구직30', 'User38', 0, 0, TO_CHAR( sysdate, 'YYYY-MM-DD' ), null, '내용_구인구직30', 0 );
INSERT INTO board VALUES( 4030, 'Recruit', '제목_구인구직31', 'User39', 0, 0, TO_CHAR( sysdate, 'YYYY-MM-DD' ), null, '내용_구인구직31', 0 );


INSERT INTO recruit VALUES( 4000, '구인' );
INSERT INTO recruit VALUES( 4001, '구인' );
INSERT INTO recruit VALUES( 4002, '구인' );
INSERT INTO recruit VALUES( 4003, '구인' );
INSERT INTO recruit VALUES( 4004, '구직' );
INSERT INTO recruit VALUES( 4005, '구인' );
INSERT INTO recruit VALUES( 4006, '구인' );
INSERT INTO recruit VALUES( 4007, '구인' );
INSERT INTO recruit VALUES( 4008, '구인' );
INSERT INTO recruit VALUES( 4009, '구인' );
INSERT INTO recruit VALUES( 4010, '구인' );
INSERT INTO recruit VALUES( 4011, '구인' );
INSERT INTO recruit VALUES( 4012, '구직' );
INSERT INTO recruit VALUES( 4013, '구직' );
INSERT INTO recruit VALUES( 4014, '구직' );
INSERT INTO recruit VALUES( 4015, '구인' );
INSERT INTO recruit VALUES( 4016, '구인' );
INSERT INTO recruit VALUES( 4017, '구인' );
INSERT INTO recruit VALUES( 4018, '구직' );
INSERT INTO recruit VALUES( 4019, '구인' );
INSERT INTO recruit VALUES( 4020, '구인' );
INSERT INTO recruit VALUES( 4021, '구인' );
INSERT INTO recruit VALUES( 4022, '구인' );
INSERT INTO recruit VALUES( 4023, '구인' );
INSERT INTO recruit VALUES( 4024, '구인' );
INSERT INTO recruit VALUES( 4025, '구직' );
INSERT INTO recruit VALUES( 4026, '구인' );
INSERT INTO recruit VALUES( 4027, '구직' );
INSERT INTO recruit VALUES( 4028, '구직' );
INSERT INTO recruit VALUES( 4029, '구직' );
INSERT INTO recruit VALUES( 4030, '구인' );

-- INSERT INTO board VALUES( BOARD_SEQ.nextval, 'Recruit', '제목_구인구직', 'User1', 0, 0, TO_CHAR( sysdate, 'YYYY-MM-DD' ), null, '내용_구인구직', 0 );
-- INSERT INTO recruit VALUES( BOARD_SEQ.currval, '구인' ); -- 시퀀스명.currval : 현재 시퀀스

-- commit;
-- DELETE recruit;
-- DELETE FROM board WHERE board_category='Recruit';