-- Reply Sample Data
SELECT reply_no, board_no, user_email, TO_CHAR(reply_create, 'YYYY-MM-DD HH24:MI:SS'), reply_content FROM reply;

INSERT INTO reply (reply_no, board_no, user_email, reply_create, reply_content) VALUES (1, 31, 'user1@naver.com', sysdate,  '댓글1');
INSERT INTO reply (reply_no, board_no, user_email, reply_create, reply_content) VALUES (2, 31, 'user2@naver.com', sysdate,  '댓글2');
INSERT INTO reply (reply_no, board_no, user_email, reply_create, reply_content) VALUES (3, 31, 'user3@naver.com', sysdate,  '댓글3');
INSERT INTO reply (reply_no, board_no, user_email, reply_create, reply_content) VALUES (4, 31, 'user4@naver.com', sysdate, '댓글4');
INSERT INTO reply (reply_no, board_no, user_email, reply_create, reply_content) VALUES (5, 31, 'user5@naver.com', sysdate, '댓글5');
INSERT INTO reply (reply_no, board_no, user_email, reply_create, reply_content) VALUES (6, 32, 'user6@naver.com', sysdate, '댓글6');
INSERT INTO reply (reply_no, board_no, user_email, reply_create, reply_content) VALUES (7, 32, 'user7@naver.com', sysdate, '댓글7');
INSERT INTO reply (reply_no, board_no, user_email, reply_create, reply_content) VALUES (8, 32, 'user8@naver.com', sysdate, '댓글8');
INSERT INTO reply (reply_no, board_no, user_email, reply_create, reply_content) VALUES (9, 32, 'user9@naver.com', sysdate, '댓글9');
INSERT INTO reply (reply_no, board_no, user_email, reply_create, reply_content) VALUES (10, 32, 'user10@naver.com', sysdate, '댓글10');
INSERT INTO reply (reply_no, board_no, user_email, reply_create, reply_content) VALUES (11, 33, 'user1@naver.com', sysdate, '댓글11');
INSERT INTO reply (reply_no, board_no, user_email, reply_create, reply_content) VALUES (12, 33, 'user2@naver.com', sysdate, '댓글12');
INSERT INTO reply (reply_no, board_no, user_email, reply_create, reply_content) VALUES (13, 33, 'user3@naver.com', sysdate, '댓글13');
INSERT INTO reply (reply_no, board_no, user_email, reply_create, reply_content) VALUES (14, 33, 'user4@naver.com', sysdate, '댓글14');
INSERT INTO reply (reply_no, board_no, user_email, reply_create, reply_content) VALUES (15, 33, 'user5@naver.com', sysdate, '댓글15');
INSERT INTO reply (reply_no, board_no, user_email, reply_create, reply_content) VALUES (16, 34, 'user6@naver.com', sysdate, '댓글16');
INSERT INTO reply (reply_no, board_no, user_email, reply_create, reply_content) VALUES (17, 34, 'user7@naver.com', sysdate, '댓글17');
INSERT INTO reply (reply_no, board_no, user_email, reply_create, reply_content) VALUES (18, 34, 'user8@naver.com', sysdate, '댓글18');
INSERT INTO reply (reply_no, board_no, user_email, reply_create, reply_content) VALUES (19, 34, 'user9@naver.com', sysdate, '댓글19');
INSERT INTO reply (reply_no, board_no, user_email, reply_create, reply_content) VALUES (20, 34, 'user10@naver.com', sysdate, '댓글20');
INSERT INTO reply (reply_no, board_no, user_email, reply_create, reply_content) VALUES (21, 35, 'user1@naver.com', sysdate, '댓글21');
INSERT INTO reply (reply_no, board_no, user_email, reply_create, reply_content) VALUES (22, 35, 'user2@naver.com', sysdate, '댓글22');
INSERT INTO reply (reply_no, board_no, user_email, reply_create, reply_content) VALUES (23, 35, 'user3@naver.com', sysdate, '댓글23');
INSERT INTO reply (reply_no, board_no, user_email, reply_create, reply_content) VALUES (24, 35, 'user4@naver.com', sysdate, '댓글24');
INSERT INTO reply (reply_no, board_no, user_email, reply_create, reply_content) VALUES (25, 35, 'user5@naver.com', sysdate, '댓글25');
INSERT INTO reply (reply_no, board_no, user_email, reply_create, reply_content) VALUES (26, 36, 'user6@naver.com', sysdate, '댓글26');
INSERT INTO reply (reply_no, board_no, user_email, reply_create, reply_content) VALUES (27, 36, 'user7@naver.com', sysdate, '댓글27');
INSERT INTO reply (reply_no, board_no, user_email, reply_create, reply_content) VALUES (28, 36, 'user8@naver.com', sysdate, '댓글28');
INSERT INTO reply (reply_no, board_no, user_email, reply_create, reply_content) VALUES (29, 36, 'user9@naver.com', sysdate, '댓글29');
INSERT INTO reply (reply_no, board_no, user_email, reply_create, reply_content) VALUES (30, 36, 'user10@naver.com', sysdate, '댓글30');
INSERT INTO reply (reply_no, board_no, user_email, reply_create, reply_content) VALUES (31, 37, 'user1@naver.com', sysdate, '댓글31');
INSERT INTO reply (reply_no, board_no, user_email, reply_create, reply_content) VALUES (32, 37, 'user2@naver.com', sysdate, '댓글32');
INSERT INTO reply (reply_no, board_no, user_email, reply_create, reply_content) VALUES (33, 37, 'user3@naver.com', sysdate, '댓글33');
INSERT INTO reply (reply_no, board_no, user_email, reply_create, reply_content) VALUES (34, 37, 'user4@naver.com', sysdate, '댓글34');
INSERT INTO reply (reply_no, board_no, user_email, reply_create, reply_content) VALUES (35, 37, 'user5@naver.com', sysdate, '댓글35');
INSERT INTO reply (reply_no, board_no, user_email, reply_create, reply_content) VALUES (36, 38, 'user6@naver.com', sysdate, '댓글36');
INSERT INTO reply (reply_no, board_no, user_email, reply_create, reply_content) VALUES (37, 38, 'user7@naver.com', sysdate, '댓글37');
INSERT INTO reply (reply_no, board_no, user_email, reply_create, reply_content) VALUES (38, 38, 'user8@naver.com', sysdate, '댓글38');
INSERT INTO reply (reply_no, board_no, user_email, reply_create, reply_content) VALUES (39, 38, 'user9@naver.com', sysdate, '댓글39');

-- commit;
-- DELETE FROM reply;