INSERT INTO board VALUES ( 3001, 'TechBoard', '제목1', 'user1@naver.com', 0, 0, TO_CHAR( sysdate,  'YYYY-MM-DD' ), null, '아무의미없다123123123123', 0 );
INSERT INTO board VALUES ( 3002, 'TechBoard', '제목2', 'user2@naver.com', 0, 0, TO_CHAR( sysdate,  'YYYY-MM-DD' ), null, '아무의미없다123123123123', 0 );
INSERT INTO board VALUES ( 3003, 'TechBoard', '제목3', 'user3@naver.com', 0, 0, TO_CHAR( sysdate,  'YYYY-MM-DD' ), null, '아무의미없다123123123123', 0 );
INSERT INTO board VALUES ( 3004, 'TechBoard', '제목4', 'user4@naver.com', 0, 0, TO_CHAR( sysdate,  'YYYY-MM-DD' ), null, '아무의미없다123123123123', 0 );
INSERT INTO board VALUES ( 3005, 'TechBoard', '제목5', 'user5@naver.com', 0, 0, TO_CHAR( sysdate,  'YYYY-MM-DD' ), null, '아무의미없다123123123123', 0 );
INSERT INTO board VALUES ( 3006, 'TechBoard', '제목6', 'user6@naver.com', 0, 0, TO_CHAR( sysdate,  'YYYY-MM-DD' ), null, '내용6', 0 );
INSERT INTO board VALUES ( 3007, 'TechBoard', '제목7', 'user7@naver.com', 0, 0, TO_CHAR( sysdate,  'YYYY-MM-DD' ), null, '내용7', 0 );
INSERT INTO board VALUES ( 3008, 'TechBoard', '제목8', 'user8@naver.com', 0, 0, TO_CHAR( sysdate,  'YYYY-MM-DD' ), null, '내용8', 0 );
INSERT INTO board VALUES ( 3009, 'TechBoard', '제목9', 'user9@naver.com', 0, 0, TO_CHAR( sysdate,  'YYYY-MM-DD' ), null, '내용9', 0 );
INSERT INTO board VALUES ( 3010, 'TechBoard', '제목10', 'user10@naver.com', 0, 0, TO_CHAR( sysdate,  'YYYY-MM-DD' ), null, '내용10', 0 );
INSERT INTO board VALUES ( 3011, 'TechBoard', '제목11', 'user1@naver.com', 0, 0, TO_CHAR( sysdate,  'YYYY-MM-DD' ), null, '내용11', 0 );
INSERT INTO board VALUES ( 3012, 'TechBoard', '제목12', 'user2@naver.com', 0, 0, TO_CHAR( sysdate,  'YYYY-MM-DD' ), null, '내용12', 0 );
INSERT INTO board VALUES ( 3013, 'TechBoard', '제목13', 'user3@naver.com', 0, 0, TO_CHAR( sysdate,  'YYYY-MM-DD' ), null, '내용13', 0 );
INSERT INTO board VALUES ( 3014, 'TechBoard', '제목14', 'user4@naver.com', 0, 0, TO_CHAR( sysdate,  'YYYY-MM-DD' ), null, '내용14', 0 );
INSERT INTO board VALUES ( 3015, 'TechBoard', '제목15', 'user5@naver.com', 0, 0, TO_CHAR( sysdate,  'YYYY-MM-DD' ), null, '내용15', 0 );
INSERT INTO board VALUES ( 3016, 'TechBoard', '제목16', 'user6@naver.com', 0, 0, TO_CHAR( sysdate,  'YYYY-MM-DD' ), null, '내용16', 0 );
INSERT INTO board VALUES ( 3017, 'TechBoard', '제목17', 'user7@naver.com', 0, 0, TO_CHAR( sysdate,  'YYYY-MM-DD' ), null, '내용17', 0 );
INSERT INTO board VALUES ( 3018, 'TechBoard', '제목18', 'user8@naver.com', 0, 0, TO_CHAR( sysdate,  'YYYY-MM-DD' ), null, '내용18', 0 );
INSERT INTO board VALUES ( 3019, 'TechBoard', '제목19', 'user9@naver.com', 0, 0, TO_CHAR( sysdate,  'YYYY-MM-DD' ), null, '내용19', 0 );
INSERT INTO board VALUES ( 3020, 'TechBoard', '제목20', 'user10@naver.com', 0, 0, TO_CHAR( sysdate,  'YYYY-MM-DD' ), null, '내용20', 0 );
INSERT INTO board VALUES ( 3021, 'TechBoard', '제목21', 'user1@naver.com', 0, 0, TO_CHAR( sysdate,  'YYYY-MM-DD' ), null, '내용21', 0 );
INSERT INTO board VALUES ( 3022, 'TechBoard', '제목22', 'user2@naver.com', 0, 0, TO_CHAR( sysdate,  'YYYY-MM-DD' ), null, '내용22', 0 );
INSERT INTO board VALUES ( 3023, 'TechBoard', '제목23', 'user3@naver.com', 0, 0, TO_CHAR( sysdate,  'YYYY-MM-DD' ), null, '내용23', 0 );
INSERT INTO board VALUES ( 3024, 'TechBoard', '제목24', 'user4@naver.com', 0, 0, TO_CHAR( sysdate,  'YYYY-MM-DD' ), null, '내용24', 0 );
INSERT INTO board VALUES ( 3025, 'TechBoard', '제목25', 'user5@naver.com', 0, 0, TO_CHAR( sysdate,  'YYYY-MM-DD' ), null, '내용25', 0 );
INSERT INTO board VALUES ( 3026, 'TechBoard', '제목26', 'user6@naver.com', 0, 0, TO_CHAR( sysdate,  'YYYY-MM-DD' ), null, '내용26', 0 );
INSERT INTO board VALUES ( 3027, 'TechBoard', '제목27', 'user7@naver.com', 0, 0, TO_CHAR( sysdate,  'YYYY-MM-DD' ), null, '내용27', 0 );
INSERT INTO board VALUES ( 3028, 'TechBoard', '제목28', 'user8@naver.com', 0, 0, TO_CHAR( sysdate,  'YYYY-MM-DD' ), null, '내용28', 0 );
INSERT INTO board VALUES ( 3029, 'TechBoard', '제목29', 'user9@naver.com', 0, 0, TO_CHAR( sysdate,  'YYYY-MM-DD' ), null, '내용29', 0 );
INSERT INTO board VALUES ( 3030, 'TechBoard', '제목30', 'user10@naver.com', 0, 0, TO_CHAR( sysdate,  'YYYY-MM-DD' ), null, '내용30', 0 );

DELETE FROM board WHERE board_category='TechBoard'; --3000 AND 3030;

-- DROP TABLE TechBoard;
-- DELETE FROM TechBoard;